src/Core/Entity/Administrator.php
<?php

namespace WS\Core\Entity;

use WS\Core\Library\Traits\Entity\BlameableTrait;
use WS\Core\Library\Traits\Entity\TimestampableTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="WS\Core\Repository\AdministratorRepository")
 * @ORM\Table(name="ws_administrator")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="ws.administrator.email_already_exists"
 * )
 */
class Administrator implements UserInterface
{
    use BlameableTrait;
    use TimestampableTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="administrator_id", type="integer", nullable=false)
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=128)
     * @ORM\Column(name="administrator_name", type="string", length=128, nullable=false)
     */
    private $name;

    /**
     * @ORM\Column(name="administrator_salt", type="string", length=32, nullable=false)
     */
    protected $salt;

    /**
     * @ORM\Column(name="administrator_password", type="string", length=128, nullable=false)
     */
    private $password;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=127)
     * @Assert\Email()
     * @ORM\Column(name="administrator_email", type="string", length=127, unique=true, nullable=false)
     */
    private $email;

    /**
     * @ORM\Column(name="administrator_active", type="boolean")
     */
    private $active;

    /**
    * @ORM\Column(name="administrator_profile", type="string", length=32, nullable=false)
    */
    private $profile;

    /**
     * @Assert\Type(type="\DateTime")
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="administrator_created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @Assert\Type(type="\DateTime")
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="administrator_modified_at", type="datetime", nullable=false)
     */
    private $modifiedAt;

    /**
     * @Assert\Length(max=128)
     * @Gedmo\Blameable(on="create")
     * @ORM\Column(name="administrator_created_by", type="string", length=128, nullable=true)
     */
    private $createdBy;

    public function __construct()
    {
        $this->salt = substr(base_convert(sha1(uniqid((string) mt_rand(), true)), 16, 36), 0, 32);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function getProfile(): ?string
    {
        return $this->profile;
    }

    public function setProfile(string $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getRoles(): array
    {
        return ['ROLE_CMS', $this->profile];
    }

    public function getSalt(): string
    {
        return $this->salt;
    }

    public function setSalt(string $salt): self
    {
        $this->salt = $salt;

        return $this;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function eraseCredentials()
    {
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(?\DateTimeInterface $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?string $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }
}

src/Core/Controller/CMS/ActivityLogController.php
<?php

namespace WS\Core\Controller\CMS;

use Symfony\Contracts\Translation\TranslatorInterface;
use WS\Core\Service\Entity\ActivityLogService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/activity-log", name="ws_activity_log_")
 */
class ActivityLogController extends AbstractController
{
    protected $translator;
    protected $service;

    public function __construct(TranslatorInterface $translator, ActivityLogService $service)
    {
        $this->translator = $translator;
        $this->service = $service;
    }

    /**
     * @Route("/", name="index")
     *
     * @param Request $request
     *
     * @return Response
     * @throws \Exception
     */
    public function index(Request $request) : Response
    {
        if (!$this->isGranted('ROLE_WS_CORE_ACTIVITY_LOG')) {
            throw $this->createAccessDeniedException($this->translator->trans('not_allowed', [], 'ws_cms'));
        }

        $page = (int) $request->get('page', 1);
        if ($page < 1) {
            $page = 1;
        }

        $limit = (int) $request->get('limit', 20);
        if (!$limit) {
            $limit = 20;
        }

        $users = $this->service->getUsers();
        $models = $this->service->getModels();

        $filters = [];

        $modelIdFilter = (int) $request->query->get('f');
        $userFilter = (string) $request->query->get('u');
        $modelFilter = (string) $request->query->get('m');
        if ($modelIdFilter > 0 && is_int($modelIdFilter)) {
            $filters['model_id'] = $modelIdFilter;
        }
        if ($userFilter !== '' && in_array($userFilter, array_map(function ($element) {
            return $element['user'];
        }, $users))) {
            $filters['user'] = $userFilter;
        }
        if ($modelFilter !== '' && in_array($modelFilter, array_map(function ($element) {
            return $element['model'];
        }, $models))) {
            $filters['model'] = $modelFilter;
        }

        $data = $this->service->getAll($filters, $page, $limit);

        $paginationData = [
            'currentPage' => $page,
            'url' => $request->get('_route'),
            'nbPages' => ceil($data['total']/$limit),
            'currentCount' => count($data['data']),
            'totalCount' => $data['total'],
            'limit' => $limit
        ];

        return $this->render(
            '@WSCore/cms/activitylog/index.html.twig',
            array_merge(
                $data,
                [
                    'paginationData' => $paginationData,
                    'params' => $request->query->all(),
                    'filters' => $filters,
                    'trans_prefix' => 'ws_cms_activity_log',
                    'users' => $users,
                    'models' => $models
                ]
            )
        );
    }
}

src/Core/Controller/CMS/AdministratorController.php
<?php

namespace WS\Core\Controller\CMS;

use WS\Core\Form\AdministratorProfileType;
use WS\Core\Service\Entity\AdministratorService;
use WS\Core\Service\ImageService;
use Symfony\Contracts\Translation\TranslatorInterface;
use WS\Core\Library\CRUD\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/administrator", name="ws_administrator_")
 */
class AdministratorController extends AbstractController
{
    protected $service;

    public function __construct(AdministratorService $service)
    {
        $this->service = $service;
    }

    protected function getRouteNamePrefix(): string
    {
        return 'ws_administrator';
    }

    protected function getTranslatorPrefix(): string
    {
        return 'ws_cms_administrator';
    }

    /**
     * @Route("/profile", name="profile")
     * @Security("is_granted('ROLE_CMS')", message="not_allowed")
     *
     * @param Request $request
     *
     * @return Response
     */
    public function profile(Request $request)
    {
        $administrator = $this->getUser();

        $form = $this->createForm(
            AdministratorProfileType::class,
            $administrator,
            [
                'translation_domain' => $this->getTranslatorPrefix()
            ]
        );

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                try {
                    $this->service->edit($administrator);

                    $this->addFlash('cms_success', $this->trans('profile.edit_success', [], $this->getTranslatorPrefix()));
                } catch (\Exception $e) {
                    $this->addFlash('cms_error', $this->trans('profile.edit_error', [], $this->getTranslatorPrefix()));
                }
            } else {
                $this->addFlash('cms_error', $this->getFormErrorMessagesList($form));
            }
        }

        return $this->render('@WSCore/cms/administrator/profile.html.twig', ['form' => $form->createView()]);
    }
}

src/Core/Controller/CMS/AssetImageController.php
<?php

namespace WS\Core\Controller\CMS;

use Symfony\Component\HttpFoundation\JsonResponse;
use WS\Core\Service\Entity\AssetImageService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use WS\Core\Service\ImageService;

/**
 * @Route("/asset-image", name="ws_asset_image_")
 */
class AssetImageController
{
    protected $service;
    protected $imageService;

    public function __construct(AssetImageService $service, ImageService $imageService)
    {
        $this->service = $service;
        $this->imageService = $imageService;
    }

    /**
     * @Route("/list", name="images")
     * @Security("is_granted('ROLE_CMS')", message="not_allowed")
     *
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function list(Request $request) : JsonResponse
    {
        $filter = (string) $request->get('f');

        $page = (int) $request->get('page', 1);
        if ($page < 1) {
            $page = 1;
        }

        $limit = (int) $request->get('limit', $this->getLimit());
        if (!$limit) {
            $limit = $this->getLimit();
        }

        $data = $this->service->getAll($filter, $page, $limit, (string)$request->get('sort'), (string)$request->get('dir'));

        $response = [];
        foreach ($data as $image) {
            $response[] = [
                'id' => $image->getid(),
                'name' => $image->getFilename(),
                'image' => $this->imageService->getImageUrl($image, 'original'),
                'thumb' => $this->imageService->getImageUrl($image, 'thumb'),
                'alt' => $image->getFilename(),
            ];
        }

        return new JsonResponse($response);
    }

    /**
     * @Route("/_save_asset_image", name="save_asset_image", methods={"POST"})
     *
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function save(Request $request)
    {
        if ($request->files->get('asset')) {
            $imageFile = $request->files->get('asset');

            $assetImage = $this->imageService->handleStandalone($imageFile, ['cropper' => []]);

            return new JsonResponse([
                'path' => $this->imageService->getImageUrl($assetImage, 'original'),
                'id' => $assetImage->getId(),
                'name' => $assetImage->getFilename()
            ]);
        }

        return new JsonResponse(['msg' => 'No asset found'], 500);
    }

    protected function getLimit() : int
    {
        return 20;
    }
}

src/Core/Controller/CMS/DashboardController.php
<?php

namespace WS\Core\Controller\CMS;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class DashboardController extends AbstractController
{
    /**
     * @Route("/", name="ws_dashboard")
     *
     * @return Response
     */
    public function index()
    {
        return $this->render('@WSCore/cms/dashboard/index.html.twig');
    }
}

src/Core/Controller/CMS/SecurityController.php
<?php

namespace WS\Core\Controller\CMS;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class SecurityController extends AbstractController
{
    protected $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @Route("/login", name="ws_cms_login")
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     * @param \Symfony\Component\Security\Http\Authentication\AuthenticationUtils $authenticationUtils
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function login(Request $request, AuthenticationUtils $authenticationUtils, AuthorizationCheckerInterface $authChecker)
    {
        if ($authChecker->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->redirectToRoute('ws_dashboard');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        if ($error instanceof \Exception) {
            // overwrite message to show invalid credentials simple message
            $error = new BadCredentialsException($this->translator->trans('login.bad_credentials', [], 'ws_cms'));
        }

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('@WSCore/cms/security/login.html.twig', [
          'last_username' => $lastUsername,
          'error' => $error,
        ]);
    }
}

src/Core/Controller/CMS/SwitchController.php
<?php

namespace WS\Core\Controller\CMS;

use WS\Core\Entity\Domain;
use WS\Core\Service\ContextService;
use WS\Core\Service\DomainService;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class SwitchController extends AbstractController
{
    protected $translator;
    protected $service;

    public function __construct(TranslatorInterface $translator, DomainService $service)
    {
        $this->translator = $translator;
        $this->service = $service;
    }

    /**
     * @Route("/switch-domain/{id}", name="ws_switch_domain", methods={"GET"})
     * @Security("is_granted('ROLE_CMS')", message="not_allowed")
     *
     * @param Request $request
     *
     * @return Response
     */
    public function switch(Request $request, $id)
    {
        $domain = $this->service->get($id);
        if ($domain instanceof Domain) {
            $session = $request->getSession();
            if ($session !== null) {
                $session->set(ContextService::SESSION_DOMAIN, $domain->getId());

                $this->addFlash('cms_success', $this->translator->trans(
                    'domain_switched',
                    [
                        '%domain%' => $domain->getHost(),
                        '%locale%' => $domain->getLocale(),
                    ],
                    'ws_cms'
                ));

                return $this->redirectToRoute('ws_dashboard');
            }
        }

        throw $this->createNotFoundException();
    }
}

src/Core/Resources/views/cms/general/alerts.html.twig
{% if has_alerts() %}
    <div class="c-dropdown dropdown u-mr-20 u-hidden-down@mobile" data-toggle="dropdown-alerts" data-component="ws_dropdown">
        <a
            href="#"
            id="alertDropdownButton"
            class="c-notification dropdown-toggle"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            title="{{ 'alerts.tooltip'|trans({ '%count%': get_alerts()|length }, 'ws_cms') }}">
            <span class="c-notification__icon">
                <i class="fal fa-bell"></i>
            </span>
            <span class="c-notification__number">{{ get_alerts()|length }}</span>
        </a>

        <div
            class="c-dropdown__menu c-dropdown__menu--large dropdown-menu dropdown-menu-right dropdown-alerts"
            aria-labelledby="alertDropdownButton"
        >
            {% for alert in get_alerts() %}
                {% if alert.routeName is not null %}
                    <a href="{{ path(alert.routeName, alert.routeOptions) }}" class="c-dropdown__item dropdown-item o-media">
                        {{ alert.message|raw }}
                    </a>
                {% else %}
                    <span class="c-dropdown__item dropdown-item o-media">
                        {{ alert.message|raw }}
                    </span>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% else %}
    <a class="c-notification" href="#" title="{{ 'alerts.tooltip'|trans({ '%count%': 0 }, 'ws_cms') }}">
        <span class="c-notification__icon">
            <i class="fal fa-bell"></i>
        </span>
        <span class="c-notification__number">{{ 'alerts.tooltip'|trans({ '%count%': 0 }, 'ws_cms') }}</span>
    </a>
{% endif %}

src/Core/Resources/views/cms/general/batch.html.twig
{% if batch_actions is not empty %}
    <div class="c-field c-field--xsmall c-choice-wrapper c-choice-wrapper--small u-mr-10 js-batchActions u-hidden">
        <select name="t" class="u-mr-10 js-batchAction" data-component="ws_select">
            <option value="">
                {{ 'actions'|trans({}, 'ws_cms') }}
            </option>
            {% for action in batch_actions %}
                {% set actionData = get_batch_action_data(action) %}

                <option value="{{ ws_cms_path("#{route_prefix}_#{actionData.route}") }}" data-title="{{ actionData.title|trans({}, 'ws_cms') }}">
                    {{ actionData.label|trans({}, 'ws_cms') }}
                </option>
            {% endfor %}
        </select>
    </div>
{% endif %}

src/Core/Resources/views/cms/general/dropdown_profile.html.twig
<div class="c-dropdown dropdown" data-toggle="dropdown-profile" data-component="ws_dropdown">
    <a
        class="c-avatar c-avatar--xsmall has-dropdown dropdown-toggle"
        href="#"
        id="dropdwonMenuAvatar"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
    >
        {# TODO integrar #}
        <i class="fal fa-user-circle fa-lg u-pr-5"></i>
        {# <img class="c-avatar__img" src="{{ asset('cms/images/avatar-72.jpg')}}" alt="{{ app.user.name }}"> #}
        {{ source('@WSCore/cms/icons/arrow.svg') }}
    </a>

    <div class="c-dropdown__menu dropdown-menu dropdown-menu-right dropdown-profile" aria-labelledby="dropdwonMenuAvatar">
        <a class="c-dropdown__item dropdown-item" href="{{ path('ws_administrator_profile') }}">
            {{ 'view_profile'|trans({}, 'ws_cms') }}
        </a>
        {% if ws_activity_log_enabled() and is_granted('ROLE_WS_CORE_ACTIVITY_LOG') %}
            <a class="c-dropdown__item dropdown-item" href="{{ path('ws_activity_log_index') }}">
                {{ 'title'|trans({}, 'ws_cms_activity_log') }}
            </a>
        {% endif %}
    </div>
</div>

src/Core/Resources/views/cms/general/footer.html.twig
<div class="row">
    <div class="col-12">
        <p class="c-footer">Powered by 
            <a class="c-footer__link" href="https://www.widestand.com" target="_blank">WideStand</a> from <a class="c-footer__link" href="https://www.acilia.es">Acilia Software</a>.
        </p>
    </div>
</div>

src/Core/Resources/views/cms/general/header.html.twig
<header class="c-navbar u-mb-medium">
    <button class="c-sidebar-toggle u-mr-small">
        <span class="c-sidebar-toggle__bar"></span>
        <span class="c-sidebar-toggle__bar"></span>
        <span class="c-sidebar-toggle__bar"></span>
    </button>

    {% set breadcrumbs = [{ 'name': 'dashboard.menu'|trans({}, 'ws_cms'), 'path': ws_cms_path('ws_dashboard') }]|merge(get_breadcrumbs()) %}

    <ol class="u-mr-auto c-breadcrumb">
        {% for breadcrumb in breadcrumbs %}
            <li class="c-breadcrumb__item {{ breadcrumb.main is defined and breadcrumb.main ? 'is-active' }}">
                {% if breadcrumb.path is defined %}
                    <a href="{{ breadcrumb.path }}">
                        {{ breadcrumb.name }}
                    </a>
                {% else %}
                    {{ breadcrumb.name }}
                {% endif %}
            </li>
        {% endfor %}
    </ol>

    {{ include('@WSCore/cms/general/language.html.twig') }}

    {{ include('@WSCore/cms/general/alerts.html.twig') }}

    <a class="c-navbar__logout u-mr-20" href="{{ app.user ? logout_path() : '' }}" title="{{ 'logout'|trans({}, 'ws_cms') }}">
        <i class="fal fa-sign-out-alt fa-lg"></i>
    </a>

    {{ include('@WSCore/cms/general/dropdown_profile.html.twig') }}

</header>

src/Core/Resources/views/cms/general/language.html.twig
{% set domains = get_domains() %}
{% if domains|length > 1 %}
    <div class="c-dropdown dropdown u-mr-20" data-toggle="dropdown-language" data-component="ws_dropdown">
        <a id="languageDropdownButton" href="#" class="c-notification u-mr-0 u-flex u-align-items-center dropdown-toggle" aria-haspopup="true" aria-expanded="false">
            <span class="c-notification__icon u-pr-5">
                <i class="fal fa-globe-europe"></i>
            </span>
            <p class="c-navbar__text u-text-xsmall u-pr-5">
                {{ ('language.' ~ get_current_domain().locale)|trans({}, 'ws_cms') }}
            </p>
            {{ source('@WSCore/cms/icons/arrow.svg') }}
        </a>

        <div
            class="c-dropdown__menu c-dropdown__menu--medium dropdown-menu dropdown-language"
            aria-labelledby="languageDropdownButton"
        >
            {% for domain in domains %}
                <a
                    href="{{ path('ws_switch_domain', { 'id': domain.id }) }}"
                    class="c-dropdown__item dropdown-item o-media {{ domain.id == get_current_domain().id ? 'is-active' }}"
                >
                    {{ domain.host }} |
                    {{ ('language.' ~ domain.locale)|trans({}, 'ws_cms') }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endif %}

src/Core/Resources/views/cms/general/nav_profile.html.twig
<a class="c-sidebar__brand" href="{{ ws_cms_path('ws_dashboard') }}" title="{{ 'name'|trans({}, 'cms') }}">
    {% if ws_cms_sidebar_has_asset('logo') %}
        <img src="{{ absolute_url(ws_cms_sidebar_get_asset('logo')) }}" />
    {% endif %}
</a>

src/Core/Resources/views/cms/general/navbar.html.twig
<header class="c-navbar u-mb-medium">
    <button class="c-sidebar-toggle js-sidebar-toggle">
        <span class="c-sidebar-toggle__bar"></span>
        <span class="c-sidebar-toggle__bar"></span>
        <span class="c-sidebar-toggle__bar"></span>
    </button>
    <div class="u-ml-auto">
        {% for menu in ws_cms_navbar_get() %}
            {% if menu.roles is empty or ws_cms_sidebar_is_granted(menu.roles) %}
                <a class="u-mr-20" href="{{ path(menu.routeName, menu.routeOptions) }}" title="{{ menu.label|trans({}, menu.translationDomain)|raw }}">
                    <i class="fal {{ menu.icon }} fa-lg"></i>
                </a>
            {% endif %}
        {% endfor %}

        {{ include('@WSCore/cms/general/language.html.twig') }}

        {{ include('@WSCore/cms/general/alerts.html.twig') }}

        <a class="c-navbar__logout u-mr-20" href="{{ app.user ? logout_path() : '' }}" title="{{ 'logout'|trans({}, 'ws_cms') }}">
            <i class="fal fa-sign-out-alt fa-lg"></i>
        </a>

        {{ include('@WSCore/cms/general/dropdown_profile.html.twig') }}
    </div>
    {% set breadcrumbs = [{ 'name': 'dashboard.menu'|trans({}, 'ws_cms'), 'path': ws_cms_path('ws_dashboard') }]|merge(get_breadcrumbs()) %}
    <ol class="c-breadcrumb">
        {% for breadcrumb in breadcrumbs %}
            <li class="c-breadcrumb__item {{ breadcrumb.main is defined and breadcrumb.main ? 'is-active' }}">
                {% if breadcrumb.path is defined %}
                    <a href="{{ breadcrumb.path }}">
                        {{ breadcrumb.name }}
                    </a>
                {% else %}
                    {{ breadcrumb.name }}
                {% endif %}
            </li>
        {% endfor %}
    </ol>
</header>

src/Core/Resources/views/cms/general/sidebar.html.twig
<ul class="c-sidebar__list">
    {% for menu in ws_cms_sidebar_get() %}
        {% if menu.roles is empty or ws_cms_sidebar_is_granted(menu.roles) %}
            {% if menu.container %}
                <li class="c-sidebar__item has-submenu {{ ws_cms_in_route(menu.collapsedRoutes, 'is-open') }}">
                    <a
                        class="c-sidebar__link"
                        href="#"
                        aria-expanded="false"
                    >
                        <i class="fal fa-1x {{ menu.icon }}" aria-hidden="true"></i>
                        <span class="c-sidebar__text">
                            {{ menu.label|trans({}, menu.translationDomain)|raw  }}
                        </span>
                        {{ source('@WSCore/cms/icons/arrow.svg') }}
                    </a>
                    <ul class="c-sidebar__submenu collapse">
                        {% for submenu in menu.children %}
                            {% if ws_cms_sidebar_is_granted(submenu.roles) %}
                                <li>
                                    <a
                                        class="c-sidebar__link js-submenu-children {{ ws_cms_in_route(submenu.collapsedRoutes, 'is-active', null, submenu.routeOptions) }}"
                                        href="{{ path(submenu.routeName, submenu.routeOptions) }}"
                                    >
                                        <i class="fal fa-1x {{ submenu.icon }}" aria-hidden="true"></i>
                                        <span class="c-sidebar__text">
                                            {{ submenu.label|trans({}, submenu.translationDomain) }}
                                        </span>
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </li>
            {% else %}
                <a
                    class="c-sidebar__link {{ ws_cms_in_route(menu.collapsedRoutes, 'is-active') }}"
                    href="{{ path(menu.routeName, menu.routeOptions) }}"
                >
                    <i class="fal fa-1x {{ menu.icon }}" aria-hidden="true"></i>
                    <span class="c-sidebar__text">
                        {{ menu.label|trans({}, menu.translationDomain)|raw  }}
                    </span>
                </a>
            {% endif %}
        {% endif %}
    {% endfor %}
</ul>

src/Core/Resources/views/cms/general/toolbar.html.twig
<form class="c-toolbar u-justify-space-between u-mb-medium" id="user_filter_form" role="form" accept-charset="UTF-8">
    <h4 class="c-toolbar__title u-mr-auto">Design Backlog</h4>

    <div class="c-field c-field--inline has-icon-right u-hidden-down@tablet u-mr-small">
        <span class="c-field__icon">
            {{ source('@WSCore/cms/icons/search.svg') }}
        </span>
        <label class="u-hidden-visually" for="navbar-search">Seach</label>
        <input class="c-input" id="navbar-search" type="text" placeholder="{{ 'search'|trans({}, 'ws_cms') }}" name="f" value="{{ app.request.get('f') }}" autocomplete="off">
    </div>
    <button type="submit" class="c-btn c-btn--info u-mr-small">{{ 'search'|trans({}, 'ws_cms') }}</button>
    <a class="c-btn c-btn--success" href="{{ ws_cms_path("#{route_prefix}_create") }}">{{ 'new'|trans({}, 'ws_cms') }}</a>
</form>